services:
  - type: web
    name: my-lumen-api
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production